name: chefstation_multivendor
description: A professional multi-vendor food delivery application built with Flutter.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core Flutter packages
  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.6.6
  
  # Storage & Preferences
  shared_preferences: ^2.3.4
  
  # Network & Connectivity
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  http_parser: ^4.1.0
  
  # Firebase Services
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  firebase_auth: ^5.3.1
  # firebase_crashlytics: ^4.0.4  # Uncomment for production
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # File & Path Management
  path_provider: ^2.1.4
  path: ^1.9.0
  file_picker: ^8.1.2
  
  # URL & Web
  url_strategy: ^0.3.0
  url_launcher: ^6.3.0
  universal_html: ^2.2.4
  flutter_inappwebview: ^6.1.4
  pointer_interceptor: ^0.10.1+2
  
  # Authentication
  pin_code_fields: ^8.0.1
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+2
  flutter_facebook_auth: ^6.0.4
  sign_in_with_apple: ^6.1.1
  
  # Location & Maps
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  location: ^6.0.0
  custom_map_markers: ^0.0.2+1
  custom_info_window: ^1.0.1
  
  # UI Components
  carousel_slider: ^5.0.0
  shimmer_animation: ^2.1.0
  photo_view: ^0.15.0
  dotted_border: ^2.1.0
  card_swiper: ^3.0.1
  expandable_bottom_sheet: ^1.1.1+1
  flutter_slidable: ^3.1.2
  just_the_tooltip: ^0.0.12
  animated_flip_counter: ^0.3.4
  marquee: ^2.2.3
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.10+1
  
  # Media & Images
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  get_thumbnail_video: ^0.7.0
  
  # Video
  video_player: ^2.9.3
  chewie: ^1.11.0
  
  # Phone & Country
  phone_numbers_parser: ^9.0.1
  country_code_picker: ^3.0.0
  
  # Sharing & Social
  share_plus: ^10.0.2
  
  # Date & Time
  intl: ^0.20.2
  syncfusion_flutter_datepicker: ^29.0.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Database
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  
  # HTML & Web Content
  flutter_widget_from_html_core: ^0.15.0
  meta_seo: ^3.0.9
  
  # Professional Development Dependencies
  # Logging & Monitoring
  logger: ^2.0.2+1
  
  # Performance Monitoring
  # flutter_performance: ^0.0.2
  
  # Security
  crypto: ^3.0.3
  encrypt: ^5.0.2
  
  # Validation
  form_validator: ^2.1.0
  
  # Caching
  # cache_manager: ^0.0.1  # Uncomment when available
  
  # Analytics
  # firebase_analytics: ^11.3.8  # Uncomment for production

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Quality
  flutter_lints: ^4.0.0
  
  # Database Development
  drift_dev: ^2.21.2
  build_runner: ^2.4.13
  
  # Testing
  mockito: ^5.4.3
  
  # Code Generation
  json_annotation: ^4.8.1
  
  # Performance Testing
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  fading_edge_scrollview: ^4.1.1
  collection: ^1.19.0
  web: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/map/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Cairo-Light.ttf
          weight: 300
        - asset: assets/font/Cairo-Regular.ttf
          weight: 400
        - asset: assets/font/Cairo-Medium.ttf
          weight: 500
        - asset: assets/font/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/font/Cairo-Bold.ttf
          weight: 700
        - asset: assets/font/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Cairo-Black.ttf
          weight: 900